name: EcmaCraft
description: Create Minecraft plugins with TypeScript using EcmaCraft
main: dev.twlite.ecmacraft.EcmaCraft
version: "0.0.1"
api-version: 1.21
author: Twilight <hello@twlite.dev>

commands:
  ecmacraft-reload:
    description: Reloads ecmacraft runtime
    usage: /ecmacraft-reload
    aliases: [escraft-reload, esc-reload]
    permission: ecmacraft.reload

permissions:
  ecmacraft.reload:
    description: Allows reloading ecmacraft runtime
    default: op