import { existsSync } from 'node:fs';
import { mkdir, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { downloadPaperMc } from './papermc.js';
import { downloadEcmacraft } from './ecmacraft.js';
import type { EcmacraftConfig } from '../../config/types.js';
import { createDevelopmentPaths } from './paths.js';

async function createEulaFile(eulaPath: string) {
  await writeFile(
    eulaPath,
    `# Autogenerated by "ecmacraft dev" command at ${new Date().toISOString()}\neula=true\n`,
    'utf-8',
  );
}

function escapeServerPropertiesValue(value: string): string {
  return value
    .replace(/\\/g, '\\\\')
    .replace(/\n/g, '\\n')
    .replace(/\r/g, '\\r')
    .replace(/\t/g, '\\t')
    .replace(/:/g, '\\:')
    .replace(/=/g, '\\=');
}

function renderServerProperties(properties: Record<string, string | number | boolean>): string {
  const header = `#Minecraft server properties\n#${new Date().toString()}\n`;

  const body = Object.entries(properties)
    .map(([key, value]) => {
      const normalizedValue = typeof value === 'boolean' ? String(value) : String(value);
      return `${key}=${escapeServerPropertiesValue(normalizedValue)}`;
    })
    .join('\n');

  return `${header}${body}\n`;
}

async function createServerPropertiesFile(
  serverPropertiesPath: string,
  properties: Record<string, string | number | boolean>,
) {
  await writeFile(serverPropertiesPath, renderServerProperties(properties), 'utf-8');
}

async function ensureDirectory(dir: string) {
  if (!existsSync(dir)) {
    await mkdir(dir, { recursive: true });
  }
}

export async function setupDevServerDirectory(cwd: string, config: EcmacraftConfig) {
  const paths = createDevelopmentPaths(cwd);
  const serverPropertiesPath = join(paths.rootDir, 'server.properties');

  await ensureDirectory(paths.rootDir);
  await ensureDirectory(paths.pluginsDir);
  await ensureDirectory(paths.ecmacraftDataDir);
  await createEulaFile(paths.eulaPath);
  await createServerPropertiesFile(serverPropertiesPath, config.development.serverProperties);

  if (!existsSync(paths.serverJarPath)) {
    await downloadPaperMc({
      version: config.development.paperVersion,
      filePath: paths.serverJarPath,
      showProgress: true,
    });
  }

  if (!existsSync(paths.ecmacraftJarPath)) {
    await downloadEcmacraft({
      filePath: paths.ecmacraftJarPath,
      showProgress: true,
    });
  }

  return paths;
}
