import { readFile, writeFile } from 'node:fs/promises';
import { join } from 'node:path';

const input = join(import.meta.dirname, '..', 'packages', 'types', 'src');

const EVENT_CLASS_REGEX = /export declare class (\w+Event)\b/g;

const source = await readFile(join(input, 'jar_types.ts'), 'utf-8');

const events = [...source.matchAll(EVENT_CLASS_REGEX)].map((match) => match);

const eventsEnum = `// Auto generated by extract-events.ts\n
export const SpigotEvents = {
${events.map((match) => `  ${match[1]}: '${match[1]}',`).join('\n')}
} as const;\n
export type SpigotEvents = typeof SpigotEvents[keyof typeof SpigotEvents];  
`;

await writeFile(join(input, 'events.ts'), eventsEnum);
